Compile native_posix with clang
* Remove freestanding flag. This caused issues with stdlib.h MB_LEN_MAX.
* Needed --for-linker flag to pass linker.cmd to clang linker.
* Build with:
    export CLANG_ROOT=/usr
    export ZEPHYR_TOOLCHAIN_VARIANT=llvm
    export CC=clang
    export CXX=clang++
    mkdir build
    cd build
    cmake -GNinja -DBOARD=native_posix -DCONFIG_ASAN=y -DCONFIG_NO_OPTIMIZATIONS=y ..
    ninja clean
    ninja
* Log:
  Zephyr version: 1.14.0
  -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.7", minimum required is "3.4")
  -- Selected BOARD native_posix
  Parsing Kconfig tree in /home/user/zephyr/Kconfig
  Loading /home/user/zephyr/boards/posix/native_posix/native_posix_defconfig as base
  Merging /home/user/zephyr/tests/net/dhcpv4/prj.conf
  Merging /home/user/zephyr/tests/net/dhcpv4/build/zephyr/misc/generated/extra_kconfig_options.conf
  Configuration written to '/home/user/zephyr/tests/net/dhcpv4/build/zephyr/.config'

  warning: TEST_RANDOM_GENERATOR (defined at subsys/random/Kconfig:8) was assigned the value 'y' but
  got the value 'n'. You can check symbol information (including dependencies) in the 'menuconfig'
  interface (see the Application Development Primer section of the manual), or in the Kconfig
  reference at
  http://docs.zephyrproject.org/latest/reference/kconfig/CONFIG_TEST_RANDOM_GENERATOR.html (which is
  updated regularly from the master branch). See the 'Setting configuration values' section of the
  Board Porting Guide as well.
  -- Cache files will be written to: /home/user/.cache/zephyr
  -- The C compiler identification is Clang 6.0.0
  -- The CXX compiler identification is Clang 6.0.0
  -- The ASM compiler identification is Clang
  -- Found assembler: /usr/bin/clang
  -- Performing Test toolchain_is_ok
  -- Performing Test toolchain_is_ok - Success
  CMake Warning at ../../../CMakeLists.txt:1470 (message):

          ------------------------------------------------------------
          --- WARNING:  __ASSERT() statements are globally ENABLED ---
          --- The kernel will run more slowly and use more memory  ---
          ------------------------------------------------------------

  -- Configuring done
  -- Generating done
  -- Build files have been written to: /home/user/zephyr/tests/net/dhcpv4/build
  [1/1] Cleaning all built files...
  Cleaning... 66 files.
  [1/99] Preparing syscall dependency handling

  [99/99] Linking C executable zephyr/zephyr.elf
  FAILED: zephyr/zephyr.elf
  : && ccache /usr/bin/clang    zephyr/CMakeFiles/zephyr_prebuilt.dir/misc/empty_file.c.obj  -o zephyr/zephyr.elf  --for-linker -T zephyr/linker.cmd -Wl,-Map=/home/user/zephyr/tests/net/dhcpv4/build/zephyr/zephyr.map -u_OffsetAbsSyms -u_ConfigAbsSyms -Wl,--whole-archive app/libapp.a zephyr/libzephyr.a zephyr/arch/arch/posix/core/libarch__posix__core.a zephyr/soc/posix/inf_clock/libsoc__posix__inf_clock.a zephyr/boards/posix/native_posix/libboards__posix__native_posix.a zephyr/subsys/net/libsubsys__net.a zephyr/subsys/net/l2/dummy/libsubsys__net__l2__dummy.a zephyr/subsys/net/ip/libsubsys__net__ip.a zephyr/subsys/testsuite/ztest/libsubsys__testsuite__ztest.a zephyr/drivers/entropy/libdrivers__entropy.a -Wl,--no-whole-archive zephyr/kernel/libkernel.a zephyr/CMakeFiles/offsets.dir/arch/posix/core/offsets/offsets.c.obj -L"/usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0" -L/home/user/zephyr/tests/net/dhcpv4/build/zephyr -lgcc -Wl,--gc-sections -Wl,--build-id=none -Wl,--sort-common=descending -Wl,--sort-section=alignment -lasan -fsanitize=address -ldl -pthread -m32 -lm && cd /home/user/zephyr/tests/net/dhcpv4/build/zephyr && /usr/bin/python3 /home/user/zephyr/scripts/check_link_map.py zephyr.map && /usr/bin/objdump -S zephyr.elf > zephyr.lst && /usr/bin/readelf -e zephyr.elf > zephyr.stat && /usr/bin/cmake -E copy zephyr.elf zephyr.exe
  /usr/bin/ld: skipping incompatible /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/libgcc.a when searching for -lgcc
  /usr/bin/ld: skipping incompatible /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/libasan.so when searching for -lasan
  /usr/bin/ld: skipping incompatible /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/libasan.a when searching for -lasan
  /usr/bin/ld: skipping incompatible /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/libgcc.a when searching for -lgcc
  /usr/bin/ld: skipping incompatible /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/libgcc_s.so.1 when searching for libgcc_s.so.1
  /usr/bin/ld: skipping incompatible /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/libgcc.a when searching for -lgcc
  /usr/bin/ld: skipping incompatible /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/libgcc.a when searching for -lgcc
  /usr/bin/ld: skipping incompatible /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/libgcc_s.so.1 when searching for libgcc_s.so.1
  /usr/bin/ld: skipping incompatible /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/libgcc.a when searching for -lgcc
  zephyr/kernel/libkernel.a(init.c.obj): In function `z_bss_zero':
  /home/user/zephyr/kernel/init.c:145: undefined reference to `__bss_end'
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.

Signed-off-by: John Andersen <john.s.andersen@intel.com>